# Generated by Django 5.1.7 on 2025-04-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'unknown')], max_length=10)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('recent_illness', models.BooleanField()),
                ('taking_antibiotics', models.BooleanField()),
                ('heart_disease', models.BooleanField()),
                ('pregnant_or_given_birth', models.BooleanField()),
                ('blood_transfusion_last_year', models.BooleanField()),
                ('traveled_malaria_risk_area', models.BooleanField()),
                ('hepatitis_or_hiv', models.BooleanField()),
                ('tattoo_or_piercing_last_six_months', models.BooleanField()),
                ('meets_eligibility', models.BooleanField()),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='ID_card/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donations', to='hospitals.hospital')),
            ],
        ),
    ]
