# Generated by Django 5.1.7 on 2025-04-06 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital'),
        ),
    ]
